export const winnerlist = [
    {
        "numseason":1,
        "title": "Alfa",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/UQcJzdy.png",
        "playart": "https://i.imgur.com/lxAzRFh.png",
        "bgseason": "https://i.imgur.com/aBylAvz.png?1",
        "narrdesc": "como vários personagens",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason":2,
        "title": "Beta",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "playart": "https://i.imgur.com/Pnufnjj.jpg",
        "bgseason": "https://i.imgur.com/WLewdyc.png",
        "narrdesc": "como Professor Cedric",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "como Rikky",
    },
    {
        "numseason":3,
        "title": "Poder da Amizade",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "playart": "https://i.imgur.com/5x0NUoI.jpg",
        "bgseason": "https://i.imgur.com/VtlGsKm.png",
        "narrdesc": "como Professor Cedric",
        "playname": "Sereia",
        "playpic": "https://i.imgur.com/0Mj5KBD.png",
        "playdesc": "",
    },
    {
        "numseason":4,
        "title": "Madrugada",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://img1.ak.crunchyroll.com/i/spire4/cce7935a6270718e12def00ae5e5753a1633089550_full.png",
        "playart": "https://i.imgur.com/pm8lCpA.png",
        "bgseason": "https://i.imgur.com/uadk8tW.png",
        "narrdesc": "como Cynthia",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "como Rikky",
    },
    {
        "numseason":5,
        "title": "Fenty Beauty Kit",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/x4NVe9C.png",
        "playart": "https://i.imgur.com/0uAF1QH.jpg",
        "bgseason": "https://i.imgur.com/TY0Y0Su.png",
        "narrdesc": "como Olivia",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason":6,
        "title": "The Gate of Hell-O-Ween",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/bu3x9m0.png",
        "playart": "https://i.imgur.com/qz2Nt2P.png",
        "bgseason": "https://i.imgur.com/b9TcDx5.gif",
        "narrdesc": "como Fantina",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason":7,
        "title": "Christmas Starlight",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i1.sndcdn.com/artworks-4wHKUmeiiI4ZTODn-4d4JEA-t500x500.jpg",
        "playart": "https://i.imgur.com/E2Zn0et.png",
        "bgseason": "https://i.imgur.com/uk6ploK.png",
        "narrdesc": "como Lusamine",
        "playname": "Sereia",
        "playpic": "https://i.imgur.com/0Mj5KBD.png",
        "playdesc": "",
    },
    {
        "numseason":8,
        "title": "Summer Vacation",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://img.women.com/images/images/000/064/261/square/misty.jpg?1484031724",
        "playart": "https://i.imgur.com/fxqsP6j.png",
        "bgseason": "https://i.imgur.com/tADquvQ.png",
        "narrdesc": "como Misty",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason":9,
        "title": "AB INITIO",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/QOMbeKW.png",
        "playart": "https://i.imgur.com/3rbC6Px.png",
        "bgseason": "https://i.imgur.com/18eFJKq.gif",
        "narrdesc": "como AZ",
        "playname": "Ken",
        "playpic": "https://i.imgur.com/AI2FHQX.png",
        "playdesc": "como Bacchant",
    },
    {
        "numseason":10,
        "title": "Victoria",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://pbs.twimg.com/profile_images/1207697988958785536/uzP0J5gd_400x400.jpg",
        "playart": "https://i.imgur.com/EPRHZX0.png",
        "bgseason": "https://i.imgur.com/eUSwBcg.png",
        "narrdesc": "como Zoey",
        "playname": "Ken",
        "playpic": "https://i.imgur.com/AI2FHQX.png",
        "playdesc": "como Bacchant",
    },
    {
        "numseason":11,
        "title": "Best Wishes",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/yTLUpQd.png",
        "playart": "https://i.imgur.com/2XamE5b.png",
        "bgseason": "https://i.imgur.com/Dou7NPw.png",
        "narrdesc": "como Lillie",
        "playname": "London",
        "playpic": "https://i.imgur.com/7rriJeo.png",
        "playdesc": "",
    },
    {
        "numseason":12,
        "title": "Vida Adulta",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/5xueYMw.png",
        "playart": "https://i.imgur.com/kkCo8qM.png",
        "bgseason": "https://i.imgur.com/eqBvohj.png",
        "narrdesc": "como Agatha",
        "playname": "Slingshot",
        "playpic": "https://i.imgur.com/hfoeYLS.jpg",
        "playdesc": "",
    },
    {
        "numseason":13,
        "title": "Work Bitch!",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/rPw8V8P.png",
        "playart": "https://i.imgur.com/QzeVxm2.png",
        "bgseason": "https://i.imgur.com/ZyEFXcI.png",
        "narrdesc": "como Professor Cedric",
        "playname": "Rob",
        "playpic": "https://i.imgur.com/LdWrXFa.jpg",
        "playdesc": "",
    },
    {
        "numseason":14,
        "title": "Mallow's Quadrille",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/JUsF3Kq.png",
        "playart": "https://i.imgur.com/fDLk0Je.png",
        "bgseason": "https://i.imgur.com/TP7ynPE.png",
        "narrdesc": "como Mallow",
        "playname": "Dean",
        "playpic": "https://i.imgur.com/RCi9485.jpg",
        "playdesc": "",
    },
    {
        "numseason":15,
        "title": "Íris, the Elementalist",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/PV0Krkm.png",
        "playart": "https://i.imgur.com/0WPkLWT.png",
        "bgseason": "",
        "narrdesc": "como Íris",
        "playname": "Luanna",
        "playpic": "https://i.imgur.com/YjHTxS7.jpg",
        "playdesc": "",
    },
    {
        "numseason": 16,
        "title": "Kids Panic!",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/xT2d2qy.png",
        "playart": "https://i.imgur.com/xbbWjRN.png",
        "bgseason": "https://i.imgur.com/YoxngrS.png",
        "narrdesc": "como Lorelei",
        "playname": "rakielle",
        "playpic": "https://i.imgur.com/zbnLEYW.png",
        "playdesc": "",
    },
    {
        "numseason": 17,
        "title": "Jingle Galar Rock",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/JhjMVU9.png",
        "playart": "https://i.imgur.com/pvBHYl4.png",
        "bgseason": "",
        "narrdesc": "como Sonia",
        "playname": "Allex",
        "playpic": "https://i.imgur.com/vSb0NZq.png",
        "playdesc": "",
    },
    {
        "numseason": 18,
        "title": "Gênesis",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/fAmx7S3.png",
        "playart": "",
        "bgseason": "",
        "narrdesc": "como Professora Júniper",
        "playname": "",
        "playpic": "https://i.imgur.com/FOdFUlO.png",
        "playdesc": "",
    },
    {
        "numseason": 19,
        "title": "Carnacenter",
        "desc": "",
        "narrname": "Rob & rakielle",
        "narrpic": "https://i.imgur.com/Lgsk1ha.png",
        "playart": "https://i.imgur.com/2nZiSIb.png",
        "bgseason": "https://i.imgur.com/VqTwuia.png",
        "narrdesc": "como Enfermeira Joy & Chansey",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason": 20,
        "title": "Vírus 20",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/7tq9lI7.png",
        "playart": "https://i.imgur.com/Xqjczve.png",
        "bgseason": "https://i.imgur.com/4toWukT.png",
        "narrdesc": "como Faba",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 21,
        "title": "Gretonika and the Sands of Time",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/wLx4nO5.png",
        "playart": "https://i.imgur.com/Tep7OVt.png",
        "bgseason": "",
        "narrdesc": "como Gretonika",
        "playname": "Biscuit",
        "playpic": "https://i.imgur.com/plJu8cw.jpg",
        "playdesc": "",
    },
    {
        "numseason": 22,
        "title": "Tropic Jungle",
        "desc": "",
        "narrname": "Dean",
        "narrpic": "https://i.imgur.com/dFbJHsM.png",
        "playart": "https://i.imgur.com/Eb9YmmT.png",
        "bgseason": "https://i.imgur.com/vdYRPFr.png",
        "narrdesc": "como Explorador Chris Pratt",
        "playname": "Biscuit",
        "playpic": "https://i.imgur.com/plJu8cw.jpg",
        "playdesc": "",
    },
    {
        "numseason": 23,
        "title": "Fundo do Poço",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/BNQn1vi.png",
        "playart": "https://i.imgur.com/FuDNS9N.png",
        "bgseason": "https://i.imgur.com/Fu4pLWL.gif",
        "narrdesc": "como Bea",
        "playname": "Miguel",
        "playpic": "https://i.imgur.com/Du00Uqp.png",
        "playdesc": "",
    },
    {
        "numseason": 24,
        "title": "Two Worlds",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/h3tYDbA.png",
        "playart": "https://i.imgur.com/9zKn6Ql.png",
        "bgseason": "https://i.imgur.com/l2EWff9.png",
        "narrdesc": "como Doutora Fennel",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 25,
        "title": "Onde está Noel?",
        "desc": "",
        "narrname": "Cazz",
        "narrpic": "https://i.imgur.com/HweHtpq.png",
        "playart": "https://i.imgur.com/hvQHrjz.png",
        "bgseason": "https://i.imgur.com/B9lQyne.png",
        "narrdesc": "como Policial Jenny",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason": 26,
        "title": "Gretonika 3: Brave New World",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/B8Rw8mu.png",
        "playart": "https://i.imgur.com/ghkFfUV.png",
        "bgseason": "https://i.imgur.com/oJTaFjd.png",
        "narrdesc": "como Professora Rita Cadillac",
        "playname": "rakielle",
        "playpic": "https://i.imgur.com/zbnLEYW.png",
        "playdesc": "",
    },
    {
        "numseason": 27,
        "title": "Um Soft Reboot",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/BNQn1vi.png",
        "playart": "https://i.imgur.com/8GTUBMg.png",
        "bgseason": "",
        "narrdesc": "como Bea",
        "playname": "Artsy",
        "playpic": "https://i.imgur.com/3su62iH.png",
        "playdesc": "",
    },
    {
        "numseason": 28,
        "title": "Festival Lunar",
        "desc": "",
        "narrname": "Dean",
        "narrpic": "https://i.imgur.com/cVdNN8T.png",
        "playart": "https://i.imgur.com/GpTKbr7.jpg",
        "bgseason": "https://i.imgur.com/Hc0S0Kq.png",
        "narrdesc": "como Drayden",
        "playname": "Miguel",
        "playpic": "https://i.imgur.com/Du00Uqp.png",
        "playdesc": "",
    },
    {
        "numseason": 29,
        "title": "Pirocópolis",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/h1KpzFR.png",
        "playart": "https://i.imgur.com/vKZYHst.png",
        "bgseason": "https://i.imgur.com/gnjVy4W.png",
        "narrdesc": "como Professor Kukui",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason": 30,
        "title": "Kill Rita",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/5j8nLsK.png",
        "playart": "https://i.imgur.com/86vwTFV.png",
        "bgseason": "https://i.imgur.com/oH5py3L.png",
        "narrdesc": "como Débora Saboya/Debiroth",
        "playname": "Dean",
        "playpic": "https://i.imgur.com/RCi9485.jpg",
        "playdesc": "",
    },
    {
        "numseason": 31,
        "title": "Planet Her",
        "desc": "",
        "narrname": "rakielle",
        "narrpic": "https://i.imgur.com/KjgGgOd.png",
        "playart": "https://i.imgur.com/QnhGIfZ.png",
        "bgseason": "https://i.imgur.com/zVYWawI.png",
        "narrdesc": "como Doja Cat",
        "playname": "Dean",
        "playpic": "https://i.imgur.com/RCi9485.jpg",
        "playdesc": "",
    },
    {
        "numseason": 32,
        "title": "Reinos",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/obILi9L.png",
        "playart": "https://i.imgur.com/9zx7ITG.jpg",
        "bgseason": "https://i.imgur.com/uldxnw3.png",
        "narrdesc": "como Columbine",
        "playname": "Biscuit",
        "playpic": "https://i.imgur.com/plJu8cw.jpg",
        "playdesc": "",
    },
    {
        "numseason": 32.5,
        "title": "Estrelas",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/BNQn1vi.png",
        "playart": "https://i.imgur.com/pZwKXI6.jpg",
        "bgseason": "",
        "narrdesc": "como Bea",
        "playname": "Marry",
        "playpic": "https://i.imgur.com/e6llepo.png",
        "playdesc": "",
    },
    {
        "numseason": 33,
        "title": "Uma Noite em Lavender Town",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/x89hEJF.jpg",
        "playart": "",
        "bgseason": "https://i.imgur.com/Yku09u8.png",
        "narrdesc": "como (Lady Veles) Columbine",
        "playname": "Rob",
        "playpic": "https://i.imgur.com/LdWrXFa.jpg",
        "playdesc": "",
    },
    {
        "numseason": 34,
        "title": "As Aventuras Maneiríssimas da Zoe",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/ZKxh8uP.jpg",
        "playart": "https://i.imgur.com/9ygw468.jpg",
        "bgseason": "https://i.imgur.com/fTcFqZy.png",
        "narrdesc": "como Zoe da Paz",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason": 35,
        "title": "Deserto Branco",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/EwIY9Oj.png",
        "playart": "https://i.imgur.com/fJvu3vj.jpg",
        "bgseason": "https://i.imgur.com/0v9XJdH.png",
        "narrdesc": "como Robever",
        "playname": "Rob",
        "playpic": "https://i.imgur.com/LdWrXFa.jpg",
        "playdesc": "",
    },
    {
        "numseason": 36,
        "title": "Frutas Frescas",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/plJu8cw.jpg",
        "playart": "https://cdn.discordapp.com/attachments/722572027843838022/967607813452988487/marry_s36.png",
        "bgseason": "https://i.imgur.com/ieeGXtp.png",
        "narrdesc": "como Biscuit",
        "playname": "Marry",
        "playpic": "https://i.imgur.com/e6llepo.png",
        "playdesc": "",
    },
    {
        "numseason": 37,
        "title": "Em Chamas",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/HAMlEbQ.png",
        "playart": "",
        "bgseason": "https://cdn.discordapp.com/attachments/971745974408069160/982051245432913980/banner.png",
        "narrdesc": "como Gretniss Mirandeen",
        "playname": "",
        "playpic": "https://i.imgur.com/FOdFUlO.png",
        "playdesc": "",
    },
    {
        "numseason": 37.5,
        "title": "New Horizon",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/6X1Pntr.png",
        "playart": "https://i.imgur.com/GXwgwXn.png",
        "bgseason": "",
        "narrdesc": "como Leon",
        "playname": "Sereia",
        "playpic": "https://i.imgur.com/0Mj5KBD.png",
        "playdesc": "",
    },
    {
        "numseason": 38,
        "title": "Arraste-me para o Inferno",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/5fBHgf1.png",
        "playart": "https://i.imgur.com/eqlQtgi.jpg",
        "bgseason": "https://i.imgur.com/3LMsNHz.png",
        "narrdesc": "como Baphomet",
        "playname": "Marry",
        "playpic": "https://i.imgur.com/e6llepo.png",
        "playdesc": "",
    },
];