export const winnerlist = [
    {
        "numseason":1,
        "title": "Alfa",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/UQcJzdy.png",
        "bgseason": "https://i.imgur.com/pkcpHlN.png",
        "narrdesc": "como vários personagens",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason":2,
        "title": "Beta",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/YngJTXo.png",
        "narrdesc": "como Professor Cedric",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "como Rikky",
    },
    {
        "numseason":3,
        "title": "Poder da Amizade",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/VjSV3zQ.png",
        "narrdesc": "como Professor Cedric",
        "playname": "Sereia",
        "playpic": "https://i.imgur.com/0Mj5KBD.png",
        "playdesc": "",
    },
    {
        "numseason":4,
        "title": "Madrugada",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://img1.ak.crunchyroll.com/i/spire4/cce7935a6270718e12def00ae5e5753a1633089550_full.png",
        "bgseason": "https://i.imgur.com/uadk8tW.png",
        "narrdesc": "como Cynthia",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "como Rikky",
    },
    {
        "numseason":5,
        "title": "Fenty Beauty Kit",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/x4NVe9C.png",
        "bgseason": "https://i.imgur.com/7ZIwaMs.png",
        "narrdesc": "como Olivia",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason":6,
        "title": "The Gates of Hell-O-Ween",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/bu3x9m0.png",
        "bgseason": "https://i.imgur.com/up04DiG.png",
        "narrdesc": "como Fantina",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason":7,
        "title": "Christmas Starlight",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i1.sndcdn.com/artworks-4wHKUmeiiI4ZTODn-4d4JEA-t500x500.jpg",
        "bgseason": "https://i.imgur.com/pOem4UI.png",
        "narrdesc": "como Lusamine",
        "playname": "Sereia",
        "playpic": "https://i.imgur.com/0Mj5KBD.png",
        "playdesc": "",
    },
    {
        "numseason":8,
        "title": "Summer Vacation",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://img.women.com/images/images/000/064/261/square/misty.jpg?1484031724",
        "bgseason": "https://i.imgur.com/fxqsP6j.png",
        "narrdesc": "como Misty",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason":9,
        "title": "AB INITIO",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/QOMbeKW.png",
        "bgseason": "https://i.imgur.com/zrLO1Qr.png",
        "narrdesc": "como AZ",
        "playname": "Ken",
        "playpic": "https://i.imgur.com/AI2FHQX.png",
        "playdesc": "como Bacchant",
    },
    {
        "numseason":10,
        "title": "Victoria",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://pbs.twimg.com/profile_images/1207697988958785536/uzP0J5gd_400x400.jpg",
        "bgseason": "https://assets.pokemon.com/assets/cms2/img/watch-pokemon-tv/seasons/season13/season13_ep19_ss02.jpg",
        "narrdesc": "como Zoey",
        "playname": "Ken",
        "playpic": "https://i.imgur.com/AI2FHQX.png",
        "playdesc": "como Bacchant",
    },
    {
        "numseason":11,
        "title": "Best Wishes",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/yTLUpQd.png",
        "bgseason": "https://i.imgur.com/kwihxrV.jpg",
        "narrdesc": "como Lillie",
        "playname": "London",
        "playpic": "https://i.imgur.com/7rriJeo.png",
        "playdesc": "",
    },
    {
        "numseason":12,
        "title": "Vida Adulta",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/5xueYMw.png",
        "bgseason": "https://i.imgur.com/kkCo8qM.png",
        "narrdesc": "como Agatha",
        "playname": "Slingshot",
        "playpic": "https://images.pandlr.com/avatars/167/1652409065-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason":13,
        "title": "Work Bitch!",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/rPw8V8P.png",
        "bgseason": "https://i.imgur.com/QzeVxm2.png",
        "narrdesc": "como Professor Cedric",
        "playname": "Rob",
        "playpic": "https://images.pandlr.com/avatars/63696/5e72dff707931-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason":14,
        "title": "Quadrilha da Mallow",
        "desc": "Primeira temporada com competitivo e torneio, dando origem ao RPG.",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/JUsF3Kq.png",
        "bgseason": "https://i.imgur.com/fDLk0Je.png",
        "narrdesc": "como Mallow",
        "playname": "Dean",
        "playpic": "https://images.pandlr.com/avatars/13415/5fb7e875bc979-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason":15,
        "title": "Íris, the Elementalist",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/PV0Krkm.png",
        "bgseason": "https://i.imgur.com/qygHRxn.png",
        "narrdesc": "como Íris",
        "playname": "Luanna",
        "playpic": "https://images.pandlr.com/avatars/42307/5d9e92c360ce5-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason": 16,
        "title": "Kids Panic!",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/xbbWjRN.png",
        "narrdesc": "como Lorelei",
        "playname": "rakielle",
        "playpic": "https://i.imgur.com/zbnLEYW.png",
        "playdesc": "",
    },
    {
        "numseason": 17,
        "title": "Jingle Galar Rock",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/pvBHYl4.png",
        "narrdesc": "como Sonia",
        "playname": "Allex",
        "playpic": "https://i.imgur.com/vSb0NZq.png",
        "playdesc": "",
    },
    {
        "numseason": 18,
        "title": "Gênesis",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/YngJTXo.png",
        "narrdesc": "como Professora Júniper",
        "playname": "",
        "playpic": "https://i.imgur.com/FOdFUlO.png",
        "playdesc": "",
    },
    {
        "numseason": 19,
        "title": "Carnacenter",
        "desc": "",
        "narrname": "Rob & rakielle",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/YngJTXo.png",
        "narrdesc": "como Enfermeira Joy & Chansey",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason": 20,
        "title": "Vírus 20",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/YngJTXo.png",
        "narrdesc": "como Faba",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 21,
        "title": "Gretonika and the Sands of Time",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/Tep7OVt.png",
        "narrdesc": "como Gretonika",
        "playname": "Biscuit",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 22,
        "title": "Tropic Jungle",
        "desc": "",
        "narrname": "Dean",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/Eb9YmmT.png",
        "narrdesc": "como Explorador Chris Pratt",
        "playname": "Biscuit",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 23,
        "title": "Fundo do Poço",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/0BJd27C.png",
        "narrdesc": "como Bea",
        "playname": "Miguel",
        "playpic": "https://i.imgur.com/Du00Uqp.png",
        "playdesc": "",
    },
    {
        "numseason": 24,
        "title": "Two Worlds",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/9zKn6Ql.png",
        "narrdesc": "como Professora Fennel",
        "playname": "Northon",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 25,
        "title": "Onde está Noel?",
        "desc": "",
        "narrname": "Cazz",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/hvQHrjz.png",
        "narrdesc": "como Policial Jenny",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason": 26,
        "title": "Gretonika 3: Brave New World",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/ghkFfUV.png",
        "narrdesc": "como Professora Rita Cadillac",
        "playname": "rakielle",
        "playpic": "https://i.imgur.com/zbnLEYW.png",
        "playdesc": "",
    },
    {
        "numseason": 27,
        "title": "Um Soft Reboot",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/RQL60vx.png",
        "narrdesc": "como Bea",
        "playname": "Artsy",
        "playpic": "https://i.imgur.com/3Ubg2d9.png",
        "playdesc": "",
    },
    {
        "numseason": 28,
        "title": "Festival Lunar",
        "desc": "",
        "narrname": "Dean",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/GpTKbr7.jpg",
        "narrdesc": "como Drayden",
        "playname": "Miguel",
        "playpic": "https://i.imgur.com/Du00Uqp.png",
        "playdesc": "",
    },
    {
        "numseason": 29,
        "title": "Pirocópolis",
        "desc": "",
        "narrname": "Rob",
        "narrpic": "https://i.imgur.com/h1KpzFR.png",
        "bgseason": "https://i.imgur.com/vKZYHst.png",
        "narrdesc": "como Professor Kukui",
        "playname": "Hydron",
        "playpic": "https://i.imgur.com/avzbWmq.png",
        "playdesc": "",
    },
    {
        "numseason": 30,
        "title": "Kill Rita",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/5j8nLsK.png",
        "bgseason": "https://i.imgur.com/86vwTFV.png",
        "narrdesc": "como Débora Saboya/Debiroth",
        "playname": "Dean",
        "playpic": "https://images.pandlr.com/avatars/13415/5fb7e875bc979-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason": 31,
        "title": "Planet Her",
        "desc": "",
        "narrname": "rakielle",
        "narrpic": "https://i.imgur.com/KjgGgOd.png",
        "bgseason": "https://i.imgur.com/QnhGIfZ.png",
        "narrdesc": "como Doja Cat",
        "playname": "Dean",
        "playpic": "https://images.pandlr.com/avatars/13415/5fb7e875bc979-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason": 32,
        "title": "Reinos",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/9zx7ITG.jpg",
        "narrdesc": "como (Lady Veles) Columbine",
        "playname": "Biscuit",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 33,
        "title": "Uma Noite em Lavender Town",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/YngJTXo.png",
        "narrdesc": "como (Lady Veles) Columbine",
        "playname": "Rob",
        "playpic": "https://i.imgur.com/PgU8h5n.png",
        "playdesc": "",
    },
    {
        "numseason": 34,
        "title": "As Aventuras Maneiríssimas da Zoe",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/9ygw468.jpg",
        "narrdesc": "como Zoe da Paz",
        "playname": "Ange",
        "playpic": "https://i.imgur.com/poZjqFc.jpg",
        "playdesc": "",
    },
    {
        "numseason": 35,
        "title": "Deserto Branco",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/fJvu3vj.jpg",
        "narrdesc": "como Robever",
        "playname": "Rob",
        "playpic": "https://images.pandlr.com/avatars/63696/5e72dff707931-bpfull.jpg",
        "playdesc": "",
    },
    {
        "numseason": 36,
        "title": "Frutas Frescas",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://cdn.discordapp.com/attachments/722572027843838022/967607813452988487/marry_s36.png",
        "narrdesc": "como Biscuit",
        "playname": "Marry",
        "playpic": "https://i.imgur.com/e6llepo.png",
        "playdesc": "",
    },
    {
        "numseason": 37,
        "title": "Em Chamas",
        "desc": "",
        "narrname": "Miguel",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/YngJTXo.png",
        "narrdesc": "como Gretniss Mirandeen",
        "playname": "",
        "playpic": "https://i.imgur.com/FOdFUlO.png",
        "playdesc": "",
    },
    {
        "numseason": 38,
        "title": "Arraste-me para o Inferno",
        "desc": "",
        "narrname": "Virizion",
        "narrpic": "https://i.imgur.com/iv07g1I.png",
        "bgseason": "https://i.imgur.com/eqlQtgi.jpg",
        "narrdesc": "como Baphomet",
        "playname": "Marry",
        "playpic": "https://i.imgur.com/e6llepo.png",
        "playdesc": "",
    },
];